---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-persistent-volume
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-exchange-pvc
spec:
  volumeName: demo-persistent-volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-exchange-pvc-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-exchange-pvc-app
  template:
    metadata:
      labels:
        app: data-exchange-pvc-app
    spec:
      containers:
      - name: data-exchange-pvc-writer
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["echo $(date) > /output/timestamp.out; sleep 3600"]
        volumeMounts:
        - name: data-exchange-pvc-volume
          mountPath: /output
      - name: data-exchange-pvc-reader
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["while [ ! -f /input/timestamp.out ]; do sleep 1; done; tail -f /input/timestamp.out"]
        volumeMounts:
        - name: data-exchange-pvc-volume
          mountPath: /input
          
      volumes:
      - name: data-exchange-pvc-volume
        persistentVolumeClaim:
          claimName: data-exchange-pvc