apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
  namespace: default
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
      <title>Mobicode config page</title>
    </head>
    <body>
      <h1>Hello, Kuberworld!</h1>
    </body>
    </html>